package tpsi

import (
    "crypto/rand"
    "math/big"
)

// sample a prime less than 2^512
func SamplePrime() (*big.Int, error) {
    return rand.Prime(rand.Reader, 512)
}

// sample a uniform random integer from the finite field generated by q (q prime)
func SampleIntFromField(q *big.Int) (*big.Int, error) {
    return rand.Int(rand.Reader, q)
}

// compute the unencrypted Hankel Matrix for the central party
func CPComputeHankelMatrix(items []int64, u *big.Int, setting Setting) BigMatrix {
    H := ComputeHankelMatrix(items, u, setting)
    return MatScaMul(H, int64(setting.n-1))
}